# -*- coding: utf-8 -*-
"""
/***************************************************************************
 XYZMesh2CSV
                                 A QGIS plugin
 xyzmesh2csv
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-22
        copyright            : (C) 2021 by orbitalnet
        email                : info@orbitalnet,jp
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load XYZMesh2CSV class from file XYZMesh2CSV.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .xyzmesh2csv import XYZMesh2CSV
    return XYZMesh2CSV(iface)
